name: publish-client

on:
  push:
    paths:
      - 'packages/client/package.json'
    branches: [main]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn
      - run: yarn build:clients
      - run: npm publish
        working-directory: ./packages/client
